version: 2.1

orbs:
  utils: ethereum-optimism/circleci-utils@1.0.13

executors:
  linux:
    machine:
      image: ubuntu-2204:2024.08.1
    resource_class: medium

jobs:
  developer-discussion-metrics:
    description: Monthly Developer Discussion Metrics Report
    executor: linux
    steps:
      - run:
          name: Get Dates for Last Month
          command: |
            # Calculate the first day of the previous month
            first_day=$(date -d "last month" +%Y-%m-01)


            # Calculate the last day of the previous month
            last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

            # Export the last_month variable for subsequent steps
            echo "export LAST_MONTH=${first_day}..${last_day}" >> $BASH_ENV
      - utils/create-github-issue-from-search:
          SEARCH_QUERY: 'repo:ethereum-optimism/developers type:discussions created:${LAST_MONTH} label:"discussion-metrics"'
          issue-title: "${LAST_MONTH} discussions question & answer report"
          issue-labels: "monthly-report"
          assignees: "sbvegan"
  developer-issue-metrics:
    description: Monthly Issue Metrics Report
    executor: linux
    steps:
      - run:
          name: Get Dates for Last Month
          command: |
            # Calculate the first day of the previous month
            first_day=$(date -d "last month" +%Y-%m-01)


            # Calculate the last day of the previous month
            last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

            # Export the last_month variable for subsequent steps
            echo "export LAST_MONTH=${first_day}..${last_day}" >> $BASH_ENV
      - utils/create-github-issue-from-search:
          SEARCH_QUERY: 'repo:ethereum-optimism/developers is:issue created:${LAST_MONTH} -reason:\"not planned\" -label:monthly-report'
          issue-title: "${LAST_MONTH} metrics report for closed issues"
          issue-labels: "monthly-report"
          assignees: "sbvegan"

  developer-pr-metrics:
    description: Monthly PR Metrics Report
    executor: linux
    steps:
      - run:
          name: Get Dates for Last Month
          command: |
            # Calculate the first day of the previous month
            first_day=$(date -d "last month" +%Y-%m-01)


            # Calculate the last day of the previous month
            last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

            # Export the last_month variable for subsequent steps
            echo "export LAST_MONTH=${first_day}..${last_day}" >> $BASH_ENV
      - utils/create-github-issue-from-search:
          SEARCH_QUERY: "repo:ethereum-optimism/developers is:pr created:${LAST_MONTH}"
          issue-title: "${LAST_MONTH} metrics report for opened prs"
          issue-labels: "monthly-report"
          assignees: "sbvegan"


# Define workflows and their triggers
workflows:
  developer-discussion-metrics-workflow:
    when:
      equal: [build_monthly, <<pipeline.schedule.name>>]
    jobs:
      - developer-discussion-metrics:
          context: circleci-repo-developers
  developer-issue-metrics-workflow:
    when:
      equal: [build_monthly, <<pipeline.schedule.name>>]
    jobs:
      - developer-issue-metrics:
          context: circleci-repo-developers
  developer-pr-metrics-workflow:
    jobs:
      - developer-pr-metrics:
          context: circleci-repo-developers 
